---
- name: Install and start Jenkins
  hosts: manager
  become: true
  tasks:
    - name: setting file permission 400 to clientfile.pem
      ansible.builtin.file:
        path: "/home/ubuntu/ci_cd/clientkey.pem"
        mode: '0400'

    - name: giving 777 permission to basic_commands.sh file
      ansible.builtin.file:
        path: "/home/ubuntu/ci_cd/basic_commands.sh"
        mode: '0777'


          
    - name: Install Java
      ansible.builtin.apt:
        name: default-jdk
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: true

    - name: Start and enable Jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true
