- name: excuting the shell script file
  hosts: manager
  become: yes
  tasks:
  - name: executing the shell file
    shell: /home/ubuntu/ci_cd/basic_commands.sh
    register: dbout

  - name: printing variable
    debug:
      var: dbout

