- name: installing services on slave1
  hosts: slave1
  become: yes
  tasks:
    - name: installing java17 in slave1
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        install_recommends: no

    - name: Create devops user
      user:
        name: devops
        state: present
        shell: /bin/bash
        create_home: yes

    - name: printing the user
      debug:
        msg: "created the devops user"

    - name: Create directory at /opt/jenkins-slave
      file:
        path: /opt/jenkins-slave
        state: directory
        owner: devops
        group: devops
        mode: '0755'
      register: file

    - name: print the file register variable
      debug:
        var: file

    - name: install the docker in slave1
      ansible.builtin.apt:
        name: docker.io
        state: present
      notify:
        - starting the docker service manully

    - name: giving the executable permission to docker.sock file
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0777'
      register: socket

    - name: printing the socket variable
      debug:
        var: socket

    - name: installing the docker compose
      ansible.builtin.apt:
        name: docker-compose
        state: present
  handlers:
   - name: starting the docker service manully
     command: systemctl start docker 
 
