apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-db
  labels:
    app: vprofile-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprofile-db
  template:
    metadata:
      labels:
        app: vprofile-db
    spec:
      containers:
      - image: vprofile/vprofiledb:V1
        name: vprofiledb
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vprofile-secret
                key: db-pass
        volumeMounts:
          - name: db-vol
            mountPath: /var/lib/mysql
      volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: vprofile-pvc

