apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: register
  name: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: register
    spec:
      containers:
      - image: {{ .Values.appimage }}
        name: register
        ports:
        - containerPort: 80
        resources: {}
status: {}
